apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-ddns-integration
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: google-ddns-integration
              image: registry.vptimmy.ddns.net/homelab/google-ddns-integration:v0.0.2
              imagePullPolicy: IfNotPresent

              resources:
                requests:
                  cpu: "50m"
                  memory: "100Mi"
                limits:
                  cpu: "200m"
                  memory: "300Mi"

              env:
                - name: GMAIL_DDNS_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: gmail-ddns-credentials
                      key: username
                - name: GMAIL_DDNS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gmail-ddns-credentials
                      key: password

          imagePullSecrets:
            - name: registry

          restartPolicy: Never
